# Generated by Django 5.2.4 on 2025-07-21 16:17

from django.db import migrations


def add_default_tags_for_birth_sex(apps, schema_editor):
    TagCategory = apps.get_model("main", "TagCategory")
    Tag = apps.get_model("main", "Tag")
    sexuality = TagCategory.objects.get(name="Sexuality")
    Tag.objects.create(name="male", category=sexuality)
    Tag.objects.create(name="female", category=sexuality)


def remove_default_tags_for_birth_sex(apps, schema_editor):
    Tag = apps.get_model("main", "Tag")
    Tag.objects.filter(name="male").delete()
    Tag.objects.filter(name="female").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_add_default_tags_and_categories"),
    ]

    operations = [
        migrations.RunPython(
            code=add_default_tags_for_birth_sex,
            reverse_code=remove_default_tags_for_birth_sex,
        )
    ]
