# Generated by Django 5.2.4 on 2025-07-22 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_add_default_tags_for_birth_sex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ai',
            options={'verbose_name': 'AI'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterModelOptions(
            name='tagcategory',
            options={'verbose_name_plural': 'Tag Categories'},
        ),
        migrations.RemoveField(
            model_name='ai',
            name='personality',
        ),
    ]
