# Generated by Django 5.2.4 on 2025-07-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_ai_options_alter_match_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai',
            name='last_execution',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ai',
            name='next_execution',
            field=models.DateTimeField(null=True),
        ),
    ]
