# Generated by Django 5.2.4 on 2025-08-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_ai_last_execution_alter_ai_next_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
