# Generated by Django 5.2.4 on 2025-08-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_message_replied_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='profile_b',
            new_name='ai_profile',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='profile_a',
            new_name='user_profile',
        ),
        migrations.AddField(
            model_name='match',
            name='do_match',
            field=models.BooleanField(default=False),
        ),
    ]
