# Generated by Django 5.2.4 on 2025-08-12 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_profile_b_match_ai_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='ai_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_ai_profile', to='main.profile'),
        ),
        migrations.AlterField(
            model_name='match',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user_profile', to='main.profile'),
        ),
    ]
