# Generated by Django 5.2.4 on 2025-08-12 15:39

from django.db import migrations


def set_do_match_values(apps, schema_editor):
    Match = apps.get_model("main", "Match")
    for match in Match.objects.all():
        match.do_match = match.do_match_a_b or match.do_match_b_a
        match.save()


def remove_do_match_values(apps, schema_editor):
    Match = apps.get_model("main", "Match")
    for match in Match.objects.all():
        match.do_match_a_b = match.do_match
        match.do_match_b_a = match.do_match
        match.save()


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_alter_match_ai_profile_alter_match_user_profile"),
    ]

    operations = [
        migrations.RunPython(
            code=set_do_match_values, reverse_code=remove_do_match_values
        ),
    ]
