# Generated by Django 5.2.4 on 2025-08-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_do_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='do_match_a_b',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='do_match_b_a',
            field=models.BooleanField(default=False),
        ),
    ]
