# Generated by Django 5.2.4 on 2025-08-12 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_match_do_match_a_b_alter_match_do_match_b_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='do_match_a_b',
        ),
        migrations.RemoveField(
            model_name='match',
            name='do_match_b_a',
        ),
    ]
