# Generated by Django 5.2.4 on 2025-08-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_remove_match_do_match_a_b_remove_match_do_match_b_a"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("def_name", models.CharField(max_length=1024, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("locked_at", models.DateTimeField(null=True)),
                ("unlocked_at", models.DateTimeField(null=True)),
                ("locked_by", models.CharField(max_length=1024, null=True)),
                ("retries", models.IntegerField(default=0)),
            ],
        ),
    ]
