# Generated by Django 5.2.4 on 2025-08-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_message_deleted_alter_message_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='def_kwargs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
