# Generated by Django 5.2.4 on 2025-08-20 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_task_def_kwargs"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Task",
        ),
    ]
