# Generated by Django 5.2.4 on 2025-08-21 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_delete_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ai",
            name="next_execution",
        ),
        migrations.RemoveField(
            model_name="ai",
            name="schedule",
        ),
    ]
