# Generated by Django 5.2.4 on 2025-08-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_remove_ai_next_execution_remove_ai_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="summarized",
            field=models.BooleanField(default=False),
        ),
    ]
