# Generated by Django 5.2.4 on 2025-08-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_message_summarized"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                max_length=150, verbose_name="first name", blank=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                max_length=150, verbose_name="last name", blank=True
            ),
        ),
    ]
