# Generated by Django 5.2.4 on 2025-08-27 16:45

from django.db import migrations


def create_default_username(apps, schema_editor):
    User = apps.get_model("main", "User")
    for user in User.objects.all():
        user.username = user.profile.username
        user.first_name = user.profile.first_name
        user.last_name = user.profile.last_name
        print("first name: " + user.first_name)
        user.save()


def remove_default_username(apps, schema_editor):
    User = apps.get_model("main", "User")
    for user in User.objects.all():
        user.username = ""
        user.first_name = ""
        user.last_name = ""
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_user_username"),
    ]

    operations = [
        migrations.RunPython(
            code=create_default_username,
            reverse_code=remove_default_username,
        )
    ]
