# Generated by Django 5.2.4 on 2025-08-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_set_default_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(default="", max_length=150, unique=True),
        ),
    ]
