# Generated by Django 5.2.4 on 2025-08-29 11:47

from django.db import migrations


def create_default_ai(apps, schema_editor):
    Ai = apps.get_model("main", "Ai")
    for ai in Ai.objects.all():
        ai.username = ai.profile.username
        ai.first_name = ai.profile.first_name
        ai.last_name = ai.profile.last_name
        ai.save()


def remove_default_ai(apps, schema_editor):
    Ai = apps.get_model("main", "Ai")
    for ai in Ai.objects.all():
        ai.username = ""
        ai.first_name = ""
        ai.last_name = ""
        ai.save()


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0027_ai_first_name_ai_last_name_ai_username"),
    ]

    operations = [
        migrations.RunPython(
            code=create_default_ai,
            reverse_code=remove_default_ai,
        )
    ]
