# Generated by Django 5.2.4 on 2025-08-29 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0028_set_default_ai"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="last_access",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="username",
        ),
    ]
