# Generated by Django 5.2.4 on 2025-08-29 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0029_remove_profile_first_name_remove_profile_last_access_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ai",
            name="last_execution",
        ),
    ]
