# Generated by Django 5.2.4 on 2025-09-10 15:21

from django.db import migrations
from datetime import date

DESCRIPTION_MIGRATION_PERFIL = "Create profile for migration #0032."


def up(apps, schema_editor):
    Profile = apps.get_model("main", "Profile")
    # Saca todos los usuarios cuyo perfil sea null.
    User = apps.get_model("main", "User")
    for user in User.objects.filter(profile__isnull=True):
        # Crea un perfil al usuario.
        profile_user = Profile.objects.create(
            height=175, birthday=date.today(), description=DESCRIPTION_MIGRATION_PERFIL
        )
        # Asocia ese perfil creado al usuario.
        user.profile = profile_user
        user.save()
    # Saca todos los perfiles de la IA que sean null.
    Ai = apps.get_model("main", "Ai")
    for ai in Ai.objects.filter(profile__isnull=True):
        # Crea un perfil para la Ai.
        profile_ai = Profile.objects.create(
            height=170, birthday=date.today(), description=DESCRIPTION_MIGRATION_PERFIL
        )
        # Asocia ese perfil creado a la Ai.
        ai.profile = profile_ai
        ai.save()


def down(apps, schema_editor):
    Profile = apps.get_model("main", "Profile")
    # Borra aquellos perfiles que tengan DESCRIPTION_MIGRATION_PERFIL
    Profile.objects.filter(description=DESCRIPTION_MIGRATION_PERFIL).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0031_alter_ai_profile_alter_user_profile"),
    ]

    operations = [migrations.RunPython(code=up, reverse_code=down)]
