# Generated by Django 5.2.4 on 2025-09-23 15:37

from django.db import migrations
from django.db.models import Count


def up(apps, schema_editor):
    Match = apps.get_model("main", "Match")
    # Encuentra las combinaciones duplicadas
    dupes = (
        Match.objects.values("user_profile", "ai_profile")
        .annotate(total=Count("id"))
        .filter(total__gt=1)
    )

    # Itera por cada combinación duplicada y conserva solo 1
    for d in dupes:
        duplicates = Match.objects.filter(
            user_profile=d["user_profile"], ai_profile=d["ai_profile"]
        ).order_by(
            "id"
        )  # por ejemplo, conserva el primero creado
        duplicates.exclude(id=duplicates.first().id).delete()


def down(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0033_alter_ai_profile_alter_user_profile"),
    ]

    operations = [
        migrations.RunPython(code=up, reverse_code=down),
    ]
