# Generated by Django 5.2.4 on 2025-09-23 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_remove_duplicated_match'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('ai_profile', 'user_profile')},
        ),
    ]
