TAGS_AND_CATEGORIES = {
    "categories": ["Personality", "Hobby", "Profession", "Sexuality", "Life Style"],
    "tags": {
        "Personality": [
            "extroverted",
            "introverted",
            "calm",
            "nervous",
            "impulsive",
            "reflective",
            "aggressive",
            "sociable",
            "solitary",
            "creative",
            "realistic",
            "analytical",
            "pessimistic",
            "optimistic",
            "narcissistic",
            "organized",
            "spontaneous",
            "romantic",
            "independent",
            "ambitious",
            "conformist",
            "responsible",
            "peaceful",
            "dependent",
            "empathetic",
            "sensitive",
            "intelligent",
            "disciplined",
            "compassionate",
            "helpful",
            "worried",
            "unstable",
            "anxious",
            "irritable",
            "cooperative",
            "assertive",
            "energetic",
            "reliable",
            "persistent",
            "docile",
            "serious",
            "adventurous",
            "passionate",
            "mature",
            "loyal",
            "disloyal",
            "dishonest",
            "honest",
            "methodical",
            "chaotic",
            "unpredictable",
            "predictable",
            "reserved",
            "impatient",
            "patient",
            "liar",
            "direct",
            "sincere",
            "competent",
            "incompetent",
            "understanding",
            "prudent",
            "critical",
            "committed",
            "manipulative",
            "animal lover",
        ],
        "Hobby": [
            "reading",
            "writing",
            "watching series",
            "watching movies",
            "film buff",
            "drawer",
            "ceramics",
            "soccer",
            "basketball",
            "sports",
            "running",
            "swimming",
            "dancing",
            "tennis",
            "golf",
            "padel",
            "crossfit",
            "gym",
            "pilates",
            "yoga",
            "content creation",
            "designing",
            "decorating",
            "gastronomy",
            "chess",
            "collecting",
            "cooking",
            "baking",
            "traveling",
            "martial arts",
            "hiking",
            "camping",
            "fishing",
            "gardening",
            "cycling",
            "surfing",
            "water sports",
            "skating",
            "skiing",
            "baseball",
            "hockey",
            "rugby",
            "listening to music",
            "music",
            "cosplay",
            "theater",
            "anime",
            "carpentry",
            "motorcycles",
            "mechanics",
            "cars",
            "programming",
            "meditation",
            "blog writing",
            "learning languages",
            "shopping",
            "playing musical instruments",
            "singing",
            "makeup",
            "discovering new places",
            "visiting museums",
        ],
        "Profession": [
            "doctor",
            "nurse",
            "pharmacist",
            "physiotherapist",
            "dentist",
            "veterinarian",
            "psychologist",
            "psychiatrist",
            "other science branches",
            "lawyer",
            "jurist",
            "prosecutor",
            "judge",
            "notary",
            "engineer",
            "computer scientist",
            "teacher",
            "carpenter",
            "mason",
            "plumber",
            "locksmith",
            "painter",
            "mechanic",
            "tailor",
            "baker",
            "butcher",
            "cook",
            "jeweler",
            "potter",
            "weaver",
            "glazier",
            "scientist",
            "biologist",
            "chemist",
            "statistician",
            "data analyst",
            "web programmer",
            "graphic designer",
            "designer",
            "community manager",
            "influencer",
            "digital content creator",
            "architect",
            "industrial engineer",
            "social worker",
            "social educator",
            "sociologist",
            "economist",
            "administrator",
            "entrepreneur",
            "journalist",
            "philologist",
            "translator",
            "sales representative",
            "sales",
            "waiter",
            "tour guide",
            "receptionist",
            "guard",
            "dancer",
            "police officer",
            "military",
            "civil guard",
            "student",
            "unemployed",
            "pilot",
            "driver",
            "truck driver",
            "surgeon",
            "astronomer",
            "self-employed",
            "model",
            "flight attendant",
            "actor",
            "actress",
            "musician",
            "others",
        ],
        "Sexuality": [
            "heterosexual",
            "homosexual",
            "bisexual",
            "asexual",
            "androsexual",
            "antrosexual",
            "bicurious",
            "demisexual",
            "polyamorous",
            "polysexual",
            "sapiosexual",
            "trans",
            "binary gender",
            "non-binary",
            "queer",
            "agender",
            "bigender",
            "gender fluid",
            "cisgender",
            "intersex",
            "transgender",
            "transsexual",
            "others",
        ],
        "Life Style": [
            "urban",
            "rural",
            "early riser",
            "night owl",
            "social",
            "homebody",
            "minimalist",
            "bohemian",
            "classic",
            "modern",
            "eco-friendly",
            "foodie",
            "traveler",
            "homey",
            "family-oriented",
            "healthy",
            "healthy habits",
            "party-goer",
            "backpacker",
        ],
    },
}
